
platform :ios, '8.0'

target 'FileCacheExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SVProgressHUD'
    
  target 'FileCacheExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FileCacheExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
